/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BalloonDetailIF.java
 *
 * Created on Jul 10, 2012, 5:41:13 PM
 */

package ETM.MONITOR;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author Hyde
 */
public class BalloonDetailIF extends javax.swing.JInternalFrame {

    /** Creates new form BalloonDetailIF */
    public BalloonDetailIF()
    {
        initComponents();
        extendComponents();
    }

    private void extendComponents()
    {
        ImageIcon IC = new javax.swing.ImageIcon(getClass().getResource("/Picz/Button16/doc_16.png"));
        this.setFrameIcon(IC);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 230, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
